spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:data.sql

security:
  jwt:
    secret: ZEFkQWZzZGdlcmxqa247cmZ3UU1ERkw7RUFHTTtFTkZXOw==
    access: 3600000
    refresh: 2592000000
